//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deVoid.UIFramework.Examples.WordChef {
    
    
    public sealed class ScreenIds {
        
        public const string HomeWindow = "Prefabs/Screens/HomeWindow";
        
        public const string SelectWorldWindow = "Prefabs/Screens/SelectWorldWindow";
        
        public const string ShopWindow = "Prefabs/Screens/ShopWindow";
    }
}
